openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /:
    get:
      operationId: listVersionsv2
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dataSetList'
        '300':
          content:
            application/json:
              schema:
                type: string
  /v2:
    get:
      operationId: getVersionDetailsv2
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dataSetList'
        '203':
          content:
            application/json:
              schema:
                type: boolean
components:
  schemas:
    dataSetList:
      type: object
      properties:
        total:
          type: integer
        apis:
          type: array
          items:
            type: object
            properties:
              apiKey:
                type: string
              apiVersionNumber:
                type: string
              apiUrl:
                type: string
                format: uriref
              apiCount:
                type: integer
                format: int64
              apiAvg:
                type: number
              isInternal:
                type: boolean
              start:
                type: string
                format: date
              apiHash:
                type: string
                format: byte