openapi: "3.0.0"
info:
  title: Simple API overview
  description: This is very simple API
  version: 2.0.0
paths:
  /:
    get:
      operationId: listVersionsv2
      summary: List API versions
      description: This is very cool API for list API versions
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dataSetList'
        '300':
          description: A bool response
          content:
            application/json:
              schema:
                type: boolean
  /v2:
    get:
      operationId: getVersionDetailsv2
      summary: List API version details
      description: This is even cooler API for listing detail versions
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  subscriptionId:
                    type: string
        '203':
          content:
            application/json:
              schema:
                type: boolean
components:
  schemas:
    dataSetList:
      description: This is data set list
      type: object
      properties:
        total:
          type: integer
        apis:
          type: array
          items:
            type: object
            description: This is apis
            properties:
              apiKey:
                type: string
              apiVersionNumber:
                type: string
              apiUrl:
                type: string
                format: uriref
              apiCount:
                type: integer
                format: int64
              apiAvg:
                type: number
              isInternal:
                type: boolean
              start:
                type: string
                format: date
              apiHash:
                type: string
                format: byte